# Generated by Django 3.2.4 on 2021-07-01 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rest',
            name='img',
            field=models.ImageField(default=5, upload_to='gallery'),
            preserve_default=False,
        ),
    ]
