# Generated by Django 3.2.4 on 2021-07-01 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0003_alter_rest_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rest',
            name='img',
            field=models.ImageField(blank=True, default='profile_img/925667.jpg', null=True, upload_to='profile_img'),
        ),
    ]
