# Generated by Django 3.2.4 on 2021-07-03 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0004_alter_rest_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rest',
            name='img',
            field=models.ImageField(default='profile_img/default.jpg', upload_to='profile_img'),
        ),
    ]
